# Generated by Django 5.2.7 on 2025-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_alter_category_options_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
    ]
